### ISSUE TITLE
Example of how to configure initialization options

### ISSUE THREAD

**Issue by pjv** [m1guer/basedpyright-zed#3]
Hi,

In my zed `settings.json`, I can configure the pyright initialzation options like this:
````
  "lsp": {
    "pyright": {
      "settings": {
        "python": {
          "pythonPath": ".venv/bin/python"
        }
      }
    },
````

I have tried every variation on similarly configuring basedpyright but cannot determine a viable syntax for globally configuring basedpyright. Can you show an example like the above that will set up the initialize options for the basedpyright extension?

Note that I am aware that I can create a `pyrightconfig.json` file in my project but that is not the solution I am looking for. I’m trying to find a way to globally configure basedpyright in my zed `settings.json`.

**Comment by m1guer** [comment]
you can create a pyproject.toml and put the all that you need inside.
like this:

```toml
[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
strict = true

[tool.django-stubs]
django_settings_module = "api_naiara_joias.settings"

[tool.basedpyright]
venvPath = "../../../.cache/pypoetry/virtualenvs/"
venv = "api-naiara-joias-YxMO4wcW-py3.12"
typeCheckingMode = "basic"
reportOptionalCall = "none"
reportOptionalMemberAccess = "none"
```
